version: "3.7"

services:
  kong-database:
    image: postgres:9.6
    container_name: kong-database
    volumes:
      - ./databases/postgres/kong_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: 12345678
    ports:
      - 5432:5432
    networks:
      - kong-net
    restart: on-failure

  kong-migration:
    build: ./kong
    container_name: kong-migration
    depends_on:
      - kong-database
    links:
      - kong-database:kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: 12345678
    # command: sh -c "(kong migrations up || kong migrations bootstrap) && touch migrations_run && sleep 30"
    command: kong migrations bootstrap
    networks:
      - kong-net
    restart: on-failure

  kong:
    build: ./kong
    container_name: kong
    depends_on:
      - kong-database
      - kong-migration
    links:
      - kong-database:kong-database
      - kong-migration:kong-migration
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: 12345678
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - 8000:8000
      - 8001:8001
      - 127.0.0.1:8443:8443
      - 127.0.0.1:8444:8444
    networks:
      - kong-net
    volumes:
      - ./kong/kong.config.default:/etc/kong/kong.conf
    restart: on-failure

  konga-database:
    image: mongo:4.1.5
    container_name: konga-database
    volumes:
      - ./databases/mongodb/konga_data:/data/db
    ports:
      - 27017:27017
    networks:
      - kong-net
    restart: on-failure

  #  kong-dashboard:
  #    image: pgbi/kong-dashboard:v3
  #    container_name: kong-dashboard
  #    depends_on:
  #      kong:
  #        condition: service_healthy
  #    command: start --kong-url http://kong:8001
  #    ports:
  #      - 8080:8080
  #    restart: on-failure

  konga:
    build: ./konga
    container_name: konga
    depends_on:
      - konga-database
    links:
      - konga-database:konga-database
    volumes:
      - ./konga/user_seed.js:/app/user_seed.js:ro
    ports:
      - 1337:1337
    environment:
      DB_ADAPTER: mongo
      DB_DATABASE: konga
      DB_HOST: konga-database
      KONGA_SEED_USER_DATA_SOURCE_FILE: /app/user_seed.js
      NODE_ENV: production
    restart: on-failure
    networks:
      - kong-net

volumes:
  kong_data:
  kong-vol:
  konga_data:

networks:
  kong-net:
    external: false